typography_spectrum: 0.4981006570160389
color:
  brandColors:
    - '#070709'
    - '#dbdfe8'
    - '#56575b'
    - '#f06d97'
    - '#ababa9'
  brandStrength: 0.25
  lightness: 0.6941330109257251
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49121
analytics:
  google: null
  facebook: null
  twitter: null
name: platypusvr
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: PLATYPUS
description: 'View, create and tell VR stories on the web'
purpose: []
